### ISSUE TITLE
Support for additional self-supervised techniques

### ISSUE THREAD

**Issue by jwuphysics** [spaceml-org/Self-Supervised-Learner#14]
Is there any plan to (flexibly) incorporate other SSL techniques? Barlow Twins does not require large batch sizes (in contrast to SimCLR), and can be easily implemented with a custom loss function using the same backbone as SimSiam ([example](https://github.com/IgorSusmelj/barlowtwins/blob/239a90316958cd72dd6696691606daef933355b3/main.py#L82)).

**Comment by RudyVenguswamy** [comment]
Hi, the way the pipeline is built, it's not too difficult to incorporate other SSL techniques. That said, for Barlow Twins, the only difference seems to be the loss function! The package is built class-oriented, so if you call model = SIMSIAM.SIMSIAM(args), and modify model.loss to be BarlowTwinsLoss it should work.

**Comment by RudyVenguswamy** [comment]
Feel free to reopen if you have issues with it!
